; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:eesp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM9
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit NeoPixel ;support for neopixel led strip
    paulstoffregen/OneWire ;support for one wire temperature sensor
    milesburton/DallasTemperature ;support for one wire temperature sensor
    bblanchon/ArduinoJson ;support for JSON handling
    knolleary/PubSubClient
    paulstoffregen/OneWire
build_src_filter = +<main.cpp>